#!/bin/bash

# Check Excel Version
# Brandon Karon

# If Excel IS installed then echo version # | If Excel is NOT installed then echo "Not Installed"

if [ -d /Applications/Microsoft\ Excel.app ] ; then

RESULT=$( sudo defaults read /Applications/Microsoft\ Excel.app/Contents/Info.plist CFBundleShortVersionString )
	echo "<result>$RESULT</result>"
else
	echo "<result>Not Installed</result>"
fi

exit 0