#!/bin/sh

# Brandon Karon
# Created: 18-11-2016
# Modified: 22-11-2016
# The purpose of this script is to identify if the "Configure My Mac" policy was executed

if [ -e /usr/local/adobeit/com.adobe.lazarus.plist ]; then

RESULT=`/usr/bin/defaults read /usr/local/adobeit/com.adobe.lazarus "configure_my_mac"`
	
echo "<result>$RESULT</result>"

else 
echo "<result>Not Configured</result>"
fi
	
exit 0