#!/bin/bash

# Brandon Karon
# Created: 15-02-2017
# Script will check if screensaver is in '/Library/Screen Savers' and/or '~/Library/Screen Savers'. If installed then EA will display "Installed". If not installed EA will display "Not Installed"

if [[ -e /Library/Screen\ Savers/Adobe\ Screensaver.saver ]] || [[ -e ~/Library/Screen\ Savers/Adobe\ Screensaver.saver ]]; then

    echo "<result>Installed</result>"
else
    echo "<result>Not Installed</result>"
fi

exit 0