#!/bin/bash

# Checks for the unmanaged plist that is placed in "/usr/local/adobeit/" during read only package and/or lab restore pacakge instaltion
# Kumaresh Kulal
# Karthikeyan Marappan


if [ -f /usr/local/adobeit/com.jamf.unmanage.plist ]; then
	
RESULT=`/usr/bin/defaults read /usr/local/adobeit/com.jamf.unmanage.plist "Status"`
	
	echo "<result>$RESULT</result>"
	
else

	echo "<result>Not Installed</result>"
	
fi

exit 0